[workspace]
authors = ["Denis Sergeev <dennis.sergeev@gmail.com>"]
channels = ["conda-forge"]
name = "lfric_egp_bench"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
download-data = { cmd = "python download_data.py", cwd = "src/scripts" }

[dependencies]
python = ">=3.13.5,<3.14"
ipykernel = ">=7.3.0,<8"
iris = ">=3.13.0,<4"
matplotlib = ">=3.10.5,<4"
pandas = ">=2.3.1,<3"
f90nml = ">=1.4.4,<2"
python-stratify = ">=0.4.0,<0.5"
windspharm = ">=2.0.0,<3"

[pypi-dependencies]
ncdump-rich = ">=0.5.2, <0.6"
aeolus = { git = "https://github.com/exoclim/aeolus.git" }
