[command]
default=merge_sources.py -d $CYLC_WORKFLOW_RUN_DIR
mirrors=merge_sources.py -d $CYLC_WORKFLOW_RUN_DIR --mirrors --mirror_loc=$MIRROR_LOC
tokens=merge_sources.py -d $CYLC_WORKFLOW_RUN_DIR --tokens
